% FUNCTION TO CREATE ID AND PATHIDFROM YEAR MONTH DAY TRIAL USER AND DEVICE 
% ID. NOTES, INPUTS MUST BE STRINGS.

% THE UNIVERSITY OF TEXAS AT DALLAS
% MULTI-INTEGRATED REMOTE SENSING AND SIMULATION (MINTS)
% CODE AUTHORED BY: SHAWHIN TALEBI

function[ID, pathID] = makeIDs(YEAR, MONTH, DAY, TRIAL, USER, DEVICE)


    ID = strcat(YEAR, '_', MONTH, '_',DAY, '_',TRIAL, '_',USER, '_',...
        DEVICE);
    pathID = strrep(ID,'_','/');

end
